### ISSUE TITLE
required SWATFarmer version

### ISSUE THREAD

**Issue by echiaradia** [biopsichas/cliwf#1]
hi @biopsichas,
i'm testing the climate workflow and I received an error related to a missing parameters "project_type". I found that it is related to SWATFarmr. I suspect it is referred to SWATFarmr version as you point to a custom version that I cannot find. Which version of the farmer should I install? I'm currently running the 4.0.1
Many thanks 
enrico

**Comment by biopsichas** [comment]
Hi Enrico,

This version is actually here.
![image](https://github.com/biopsichas/cliwf/assets/49399808/e5d928d7-c105-4543-904e-d1d247cb3d66)

But I suppose your version should work too, as Christoph updated it. I assume this problem should be solved with frm <- SWATfarmR::farmr_project$new(project_name = 'frm', project_path = pth, project_type = 'environment') on the line 53 of functions.R

But I am yet to test it. If you do, let me know. 

This was information from Christoph
_____
_so there is now a new farmR version which can do both incremental saving
into databases (still the default option) and saving in the R
environment and writing everything into the .farm file at the end.

The two different project types cannot be converted from one into the
other. But I think this is not really necessary. You can define which
type of project you want to initiate the following

new_farmr('lrew_demo', proj_path, project_type = 'environment')
new_farmr('lrew_demo', proj_path, project_type = 'database')

 From then on the schedule and data handling is done internally as usual.

Hope that this works now better with Svajunas' climate workflow._

**Comment by echiaradia** [comment]
Hi @biopsichas , editing the function.r file resolve the issue. Many thanks, enrico
