### ISSUE TITLE
Any advice on memory usage restrictions / Linux?

### ISSUE THREAD

**Issue by moritzshore** [biopsichas/cliwf#3]
Having a lot of problems with our virtural machine crashing due to unrestricted use of memory by the multi-core stuff.

From what I've read, this works much better on Linux with `fork()`'ing. Any experiences with this workflow on linux before I dive in?

Or experiences with memory restriction on windows?

I'll try to figure it out on my own for now, but if anyone has advice, i'm all ears!

@michstrauch ?

**Comment by moritzshore** [comment]
@michstrauch not sure if tagging works here but i'll try it out

**Comment by michstrauch** [comment]
Hi Mo,  
I am in a rush, but for now: Wait before you dive into Linux forking. It won't work without a SWAT executable compiled for Linux.  
Is there any chance in the climate workflow to restrict the number of threads to be you used? I did not yet run it myself ...
  
Cheers

**Comment by moritzshore** [comment]
Ok thanks, no rush micha! I'll stick with the windows stuff for now and see what I can do. 

Sidenote:  in our `print.prt`  `basin_wb` is actually on line 11 not 10. Not sure if this is just a quirk in our setup, a quick in your setup, or just a typo. nevertheless, letting you know just in case. 

![image](https://github.com/biopsichas/cliwf/assets/99182918/407bca12-1d92-48c9-b801-d4d4f77810cc)


Best! 

ps. @NataljaC is the linux version of `Rev_61_0_64rel` already available somewhere?

**Comment by NataljaC** [comment]
We have successfully compiled the Linux exe, but we need to wait for all the collaborators to approve the changed that are made in the code. ETA ~ week.

Hope this is okay with you.

Natalja

**Comment by biopsichas** [comment]
> Ok thanks, no rush micha! I'll stick with the windows stuff for now and see what I can do.
> 
> Sidenote: in our `print.prt` `basin_wb` is actually on line 11 not 10. Not sure if this is just a quirk in our setup, a quick in your setup, or just a typo. nevertheless, letting you know just in case.
> 
> ![image](https://private-user-images.githubusercontent.com/99182918/308670233-407bca12-1d92-48c9-b801-d4d4f77810cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1Mzg4OTUsIm5iZiI6MTcwOTUzODU5NSwicGF0aCI6Ii85OTE4MjkxOC8zMDg2NzAyMzMtNDA3YmNhMTItMWQ5Mi00OGM5LWI4MDEtZDRkNGY3NzgxMGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3NDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NDdhZWU5ZDRkNmNlOGI5YmYxMjVlMDA5MjJmYTY5ODUwMGIwZDFiNDNkYmFlMmRlNzRiZTU1MzIwMDQwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.esTZ1phaWC35RWNicR_RqvrAo6adJEpzY2JXpPwlKZ4)
> 
> Best!
> 
> ps. @NataljaC is the linux version of `Rev_61_0_64rel` already available somewhere?

Thank Moritz, print thing was my error. Now updated.
