### ISSUE TITLE
"rcp45_rcm3_F" is missing about a month of data in 2099. 

### ISSUE THREAD

**Issue by moritzshore** [biopsichas/cliwf#5]
Just for your information:

![image](https://github.com/biopsichas/cliwf/assets/99182918/261b33b0-b29f-4bfb-b80c-c127189234e3)

Timeseries ends on day 335 (at least for CS10), this causes FarmR to give an error if you try to schedule til end of 2099. 

**Our current workaround is: only running to 2098.** 

@CsillaFarkas

**Comment by biopsichas** [comment]
Hi Moritz, 

This is correct. I have not updated this on the main branch, but on sv_dev. It is included. 

![image](https://github.com/biopsichas/cliwf/assets/49399808/8dfe389c-ca87-462d-898e-4b67b13d846e)

**Comment by moritzshore** [comment]
Ah ok -- great. Feel free to close the issue then. Or leave it up as a warning!
