### ISSUE TITLE
Question: What are grain units??

### ISSUE THREAD

**Issue by moritzshore** [biopsichas/cliwf#6]
https://github.com/biopsichas/cliwf/blob/403bad86f16adb6370fd2ebb17d0c97292664103/settings.R#L38-L41

Could someone shed some light on what grain units are? A little confused here. 

I saw the documentation here:

```
### collect cropping information for all scenarios - grain units and cultivated 
## hectare average annual
## define 1) path, 2) crop selection, 3) type of output: a) yield, b) ha, 4) 
## specify grain units equivalent for 
#  all of the selected crops (if you just keep the parameter 'grain_units', 
## there is already a parameterisation for 
#   'wwht', 'akgs', 'wbar', 'wira', 'csil', 'wiry', 'sgbt','barl'
# the measure list (measr.list) can be adapted to the measures you want to compare
```

But I still don't really understand what they are. 

We need the grain units for `swht`, `oats` and `pota`. 

In-case not resolved by thursday, @CsillaFarkas will mention in the QA.

I guess @michstrauch might know the answer?

**Comment by michstrauch** [comment]
This has been copied from the measure scenario workflow, where it is now shortly explained as follows:
```
#If you want to use grain units to normalize the basin wide sum of crop yields by crop-specific
# nutritional values, please specify grain units for relevant crops
# The grain units must be applicable to dry mass!!!
```
Grain units are optional but recommended (the farm advisor in our German MARG made us aware of that, it makes sense to normalize the sum of crop yields). It should be ok to use the grain units defined in the script, but if values for some of your crops are missing you need to search on your own (but again: no must! - not including it in the report/plot is fine)

**Comment by michstrauch** [comment]
OK, I asked Felix to look for swht, oats and pota. Let's see. Will tell you in the QA.

**Comment by michstrauch** [comment]
Btw: Svajunas cheated and just defined 1 for all of his missing crops. These are the values we looked up for the German case:
  
```
grain_units <- data.frame('wbar' = 1.163, 
                          'csil' = 1.071, 
                          'wwht' = 1.209, 
                          'wira' = 1.429,
                          'barl' = 1.163,
                          'akgs' = 0.682, 
                          'wiry' = 1.174, 
                          'sgbt' = 1)
```

**Comment by moritzshore** [comment]
Ok,  thanks for all the info! -- if felix finds the values for our 3 missing crops that would be a big help.

and -- yeah we've got the missing ones as 1.0 for now as well. 

Scenario runs are currently cooking in the VM, should be done in the next hour(s)!
